name: Issue Closed Event

on:
  issues:
    types:
      - closed

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check for "payment" label
        id: check_label
        run: |
          issue_labels=$(jq -r '.issue.labels[].name' $GITHUB_EVENT_PATH)
          echo "::set-output name=has_payment_label::false"

          for label in $issue_labels; do
            if [ "$label" == "payment" ]; then
              echo "::set-output name=has_payment_label::true"
              break
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Get Issue Assignee
        id: get_assignee
        run: |
          issue_assignee="${{ github.event.issue.assignee.login }}"
          echo "::set-output name=assignee::${issue_assignee}"

      - name: Hash Assigned User
        id: assignee
        if: steps.check_label.outputs.has_payment_label == 'true' && steps.get_assignee.outputs.assignee != 'null'
        run: |
          hash=$(echo -n ${{ steps.get_assignee.outputs.assignee }} | sha256sum | awk '{print $1}')
          hex=0x$hash
          echo "::set-output name=hash::$hex"

      - name: Call contract
        id: approve
        uses: kudos-ink/approve@392c8b5c1fb19fae92163827c964cef06155e377
        if: steps.check_label.outputs.has_payment_label == 'true' && steps.pr_info.outputs.assignee != 'null'
        with:
          ws-provider-url: ${{ vars.WS_PROVIDER_URL }}
          mnemonic-phrase: ${{ secrets.MNEMONIC_PHRASE }}
          contract-address: ${{ vars.CONTRACT_ADDRESS }}
          contract-abi: ${{ vars.ABI }}
          contribution-id: ${{ github.event.issue.id }}
          contributor-identity: ${{ steps.assignee.outputs.hash }}

      - name: Print Output
        id: output
        if: steps.check_label.outputs.has_payment_label == 'true' && steps.get_assignee.outputs.assignee != 'null'
        run: |
          echo "tx hash ${{ steps.approve.outputs.hash }}"
          echo "block ${{ steps.approve.outputs.block }}"
          echo "issue id ${{ github.event.issue.id }}"
